'use client';
import { useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { renderManualRegionFinal } from '@/lib/api';
import { useTimelineStore, type RegionBox } from '@/store/timelineStore';
const VIDEO_W=1920, VIDEO_H=1080; const clamp=(v:number,min:number,max:number)=>Math.min(Math.max(v,min),max);
export default function ManualRegionPage(){const router=useRouter(); const {analysis_id}=useParams<{analysis_id:string}>(); const {videoUrl,analysisId,hydrateFromBackend,manualRegion,setManualRegion,setClipRenderMode}=useTimelineStore(); const playerRef=useRef<HTMLDivElement|null>(null); const isDraggingRef=useRef(false); const [dragOrigin,setDragOrigin]=useState<{x:number;y:number;region:RegionBox}|null>(null);
useEffect(()=>{if(analysis_id&&analysisId!==analysis_id){if(isDraggingRef.current){console.log('[MANUAL REGION HYDRATE BLOCKED]');return;} void hydrateFromBackend(analysis_id);} setClipRenderMode('manual_region');},[analysis_id,analysisId,hydrateFromBackend,setClipRenderMode]);
const onDown=(e:React.PointerEvent)=>{e.preventDefault();isDraggingRef.current=true;console.log('[MANUAL REGION DRAG START]');setDragOrigin({x:e.clientX,y:e.clientY,region:manualRegion});};
const onMove=(e:React.PointerEvent)=>{if(!dragOrigin||!playerRef.current)return;const rect=playerRef.current.getBoundingClientRect();const dx=(e.clientX-dragOrigin.x)*(VIDEO_W/rect.width);const dy=(e.clientY-dragOrigin.y)*(VIDEO_H/rect.height);setManualRegion({...manualRegion,x:clamp(dragOrigin.region.x+dx,0,VIDEO_W-manualRegion.width),y:clamp(dragOrigin.region.y+dy,0,VIDEO_H-manualRegion.height)},{persist:false});};
const onUp=()=>{if(!dragOrigin)return;setDragOrigin(null);isDraggingRef.current=false;setManualRegion(manualRegion,{persist:true});console.log('[MANUAL REGION DRAG END]');};
const confirm=async()=>{await renderManualRegionFinal({analysis_id,render_mode:'manual_region',manual_region:manualRegion});router.push(`/editor?analysis_id=${analysis_id}`);};
return <main className='min-h-screen bg-slate-950 p-6 text-white'><div className='mx-auto max-w-5xl'><h1 className='mb-3 text-3xl'>Manual Region Setup</h1><div ref={playerRef} onPointerMove={onMove} onPointerUp={onUp} onPointerCancel={onUp} className='relative overflow-hidden rounded-xl border border-white/20'>{videoUrl?<video src={videoUrl} className='aspect-video w-full object-cover' controls/>:<div className='grid aspect-video place-items-center'>Sem vídeo</div>}<div onPointerDown={onDown} className='absolute cursor-move border-2 border-cyan-300 bg-cyan-300/20' style={{left:`${manualRegion.x/VIDEO_W*100}%`,top:`${manualRegion.y/VIDEO_H*100}%`,width:`${manualRegion.width/VIDEO_W*100}%`,height:`${manualRegion.height/VIDEO_H*100}%`}} /></div><button onClick={confirm} className='mt-4 rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-black'>Confirmar Manual Region</button></div></main>;}
